name: 'simclr-base_debug'
encoder:
  type: 'thinresnet34'
model:
  type: 'simclr'
training:
  epochs: 100
  batch_size: 4
  learning_rate: 0.001
dataset:
  max_samples: 100
  frame_length: 64000
  frame_split: true
  extract_mfcc: true
  train: './data/debug.scp'
  test: './data/debug.scp'