name: 'vicreg_b256_mlp_none'
encoder:
  type: 'thinresnet34'
model:
  type: 'simclr'
  enable_mlp: false
  infonce_loss_factor: 0.0
  vic_reg_factor: 1.0
training:
  epochs: 500
  batch_size: 256
  learning_rate: 0.001
dataset:
  frame_length: 32000
  frame_split: true
  extract_mfcc: true
  train: './data/voxceleb1_train_list'
  val_ratio: 0.0
  spec_augment: false
  wav_augment:
    enable: true